version: "3.8"
services:
  app:
    command: /bin/bash -c "dum i && dum rw dev"
    build: .
    working_dir: /app
    volumes:
      - ./redwoodblog:/app
    environment:
      - RWJS_DEV_API_URL=${RWJS_DEV_API_URL:-http://localhost}
      - SESSION_SECRET=${SESSION_SECRET:-dummy}
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?connection_limit=1
      - TEST_DATABASE_URL=postgres://postgres:postgres@db-test:5432/postgres_test?connection_limit=1
    ports:
      - "7910:7910" # storybook
      - "8910:8910" # redwoodjs web
      - "8911:8911"
      - "18911:18911"
      - "5555:5555"
    depends_on:
      - db
      - db-test
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./redwoodblog/.db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  db-test:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_test
    volumes:
      - ./redwoodblog/.db/data-test:/var/lib/postgresql/data
    ports:
      - "5433:5432"
